### ISSUE TITLE
Support for aliases and/or H1

### ISSUE THREAD

**Issue by dariuskramer** [namikaze-40p/obsidian-tab-selector#1]
Hi!

Would it be possible to add support for the `aliases` property and/or the H1 of the notes?

Thx.

**Comment by namikaze-40p** [comment]
Thanks for the request!

I think I can provide the display of `aliases` properties. I will consider it.
I have not yet found a way to provide the display of the `H1`. So I may not be able to provide.

The support time has not been determined yet, but please wait.

**Comment by namikaze-40p** [comment]
Fixed in [this commit](https://github.com/namikaze-40p/obsidian-tab-selector/commit/315fb8cfa7647443dba39455fbdaf031fba8c35b).

Aliases is supported in version 0.3.0.
