### ISSUE TITLE
feature request, close tabs

### ISSUE THREAD

**Issue by aikruger** [namikaze-40p/obsidian-tab-selector#2]
This is a great add-in. Could I request that you add the option to close each tab in the pop up tab selector? Maybe by adding a close x to the right of each tab bar in the selector

**Comment by namikaze-40p** [comment]
@aikruger 
Thanks for the request!

Which of the following is closest to your request?
Or would you prefer another pattern?

## Pattern A
When you open the pop-up tab selector, do you want to close several tabs at once?

1. Open pop up tab selector.
1. Close several tabs.
1. Close pop up tab selector.

## Pattern B
When you open the pop-up tab selector, do you want to close only one tab at once?

1. Open pop up tab selector.
1. Close one tab.
1. Close pop up tab selector.

**Comment by namikaze-40p** [comment]
Maybe is this what the actual use case looks like?

1. Open pop up tab selector.
1. Close several tabs.
1. Select and open tab (auto close up tab selector).

**Comment by aikruger** [comment]
Your last case is the most flexible. 
1. Open pop up tab selector
2.  Close one or more tabs (selecting x on each tab)
3. Select and open tab (auto close up tab selector)

**Comment by namikaze-40p** [comment]
Thanks for your reply!
OK, I’ll consider it.
It'll be supported in version 0.4.0.

**Comment by namikaze-40p** [comment]
@aikruger 
I added new options for close tabs in [v0.4.0](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.4.0).  
Try it if you like.
