### ISSUE TITLE
Tab switching delay and latest update problem

### ISSUE THREAD

**Issue by N3C2L** [namikaze-40p/obsidian-tab-selector#5]
1. I want to ask you if it's possible to reduce the delay between tab switch to a minimum? Because I can already notice the delay when pressing for example ctrl+tab. There is a longer delay so that you have to press the keys longer in order to switch tabs.

2. Latest update fails to install:
Inside Obsidian I can't update the plugin to the latest version.
Can you check this in a sandbox vault? It should update to your latest version 0.5.8.

Thanks for the help!

**Comment by namikaze-40p** [comment]
Thanks for your request!

---
> I want to ask you if it's possible to reduce the delay between tab switch to a minimum?

There isn't much that can be done, but I'll consider it because I can think of several ways to do it.

---
> Latest update fails to install:

I checked and could install it in a sandbox vault.
What's the version of your Obsidian?
The latest version(v0.5.8,) of the plugin, requires Obsidian version 1.6.3.

**Comment by N3C2L** [comment]
Yeah, my bad, sorry! I did have the previous version installed, but updated obsidian and your plugin can update to the freshest version now. Thanks!
About the delay: I'd be glad if you find a way to decrease the delay. If you compare it with the alt+tab speed of Windows OS then you will notice the difference.

**Comment by namikaze-40p** [comment]
I released it in [v0.5.9](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.5.9).
Could you check if there has been an improvement?

**Comment by N3C2L** [comment]
It's much better with your update now! 
Thanks!
I think I can close this issue.

**Comment by namikaze-40p** [comment]
Thanks for checking!
