### ISSUE TITLE
Show one-letter key to jump to tab as hints

### ISSUE THREAD

**Issue by PLRrex** [namikaze-40p/obsidian-tab-selector#6]
Hi. Firstly thank you for this very useful plugin.

I'd like to ask if it's possible to have a "no modal window mode" which shows only the one-letter keys currently in the "Open tab selector" command as hints/tooltips at the tab headers instead. (Visually, it would look like jump hints from the [Jump to Link](https://github.com/mrjackphil/obsidian-jump-to-link) plugin or Firefox's [tridactyl](https://github.com/tridactyl/tridactyl) addon.)

This would allow for a smoother and more visual jumping experience by first looking at the header of the target tab, pressing some hotkeys to show hints for all the tabs (while still looking at the target tab), then pressing the hint that comes up, to jump to that tab.

Thank you in advance.

**Comment by namikaze-40p** [comment]
@nuanjanP 
Thanks for your request!

I released it in [v0.6.0](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.6.0)
Try it if you like.

**Comment by PLRrex** [comment]
Wow, thank you very much! 😊
