### ISSUE TITLE
feature request: allow us to type to search open tabs

### ISSUE THREAD

**Issue by RedemptionC** [namikaze-40p/obsidian-tab-selector#7]
I think it'd be more intuitive, or at least it'd serve as a good option :)

**Comment by namikaze-40p** [comment]
@RedemptionC 
Thanks for your request! Sorry for the late reply
I’ll consider your request, please wait for a while.

**Comment by namikaze-40p** [comment]
Sorry for the late response.

I released it in [v0.7.0](https://github.com/namikaze-40p/obsidian-tab-selector/releases/tag/0.7.0).
Try it if you like.
